### ISSUE TITLE
Extract data from three test cases from Dan

### ISSUE THREAD

**Issue by iangow** [iangow/ct_orders#1]
It seems that the latest code is working with these:

### Using the R code-created table:

```sql
WITH test_cases AS (
    SELECT file_name
    FROM ct_orders.raw_text 
    WHERE order_text ~ '(333-172792|1-10581 - CF# 21943|001-07882 - CF# 22815)')

SELECT *
FROM ct_orders.processed_data
INNER JOIN test_cases
USING (file_name);
```

### Using the Python code-created table:
```sql
WITH test_cases AS (
    SELECT file_name
    FROM ct_orders.raw_text 
    WHERE order_text ~ '(333-172792|1-10581 - CF# 21943|001-07882 - CF# 22815)')

SELECT *
FROM ct_orders.processed_data_py
INNER JOIN test_cases
USING (file_name);
```

Output from either looks more or less like this:

```
                  file_name                  |   form    |      form_date      | denied | granted |                           exhibits                           
---------------------------------------------+-----------+---------------------+--------+---------+--------------------------------------------------------------
 edgar/data/821616/9999999997-08-028554.txt  | Form 10-K | 2002-02-15 00:00:00 | f      | t       | {"Exhibit 10.10(a)","Exhibit 10.10(c)"}
 edgar/data/2488/9999999997-09-003559.txt    | Form 10-Q | 2008-11-06 00:00:00 | f      | t       | {"Exhibit 2.1","Exhibit 10.1","Exhibit 10.2","Exhibit 10.3"}
 edgar/data/1093207/9999999997-11-014860.txt | Form S-1  | 2011-03-11 00:00:00 | f      | t       | {"Exhibit 10.11"}
(3 rows)
```

**Comment by claireypark** [comment]
Dear Ian,


I apologize again for the super late reply! I finished my full-time RA work last week and have been traveling Europe since then, so I was connected to internet only sporadically over the past week (and my phone strangely did not let me send email through this account). I have finally found a good place to work with my laptop, so I successfully ran the Python code on my computer and got the final CSV file that lists all the information exactly as you described. Thank you so much for this! You are indeed the coding guru as Dan told me. The code seems to work perfectly fine (I have used the code you most recently modified). You have already written up so much (and beautifully) that there is hardly any work left for me to do. All I have left is :


1. Include another function similar to extract_details() and form_date() that extracts the "through" date for those "granted" forms

2. Slightly change the exhibits extraction part to make it so that each observation is at firm id-file date-form-exhibit level, since right now, it is at firm id-file date-form level.


I will make these two changes and submit to the repository if it turns out to be successful! Meanwhile, please let me know if I have understood anything counter to what you intended in your code. Also, I will be returning home in about four days, so I will be able to communicate a lot better soon. Thank you again for your patience and your help.



Sincerely,


Yeayeun




________________________________
